site_name: 南京大学《软件质量与管理》期末复习
site_description: 敏捷软件开发 — 课堂小测在线答题系统
site_author: 南京大学
edit_uri: ""

theme:
  name: material
  language: zh
  # palette:
  #   primary: amber
  #   accent: amber
  #   scheme: default
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono

extra:
  analytics:
    provider: google
    property: G-CDTMFQ2S7D

nav:
  - 首页: index.md
  - 必背指南: recite.md
  - 课程总结必背: final-recite.md
  - 课堂小测: quiz/index.html
  - 课堂小测答案: exams/quiz-answers.md
  - 往年试题解答:
      - 课上选择题: exams/classroom-quiz.md
      - 2023年A卷: exams/2023.md
      - 2022年: exams/2022.md
      - 2021年: exams/2021.md
      - 2020年期中考: exams/2020.md
      - 2018年: exams/2018.md
      - 2016年: exams/2016.md
      - 2015年: exams/2015.md
      - 2014年: exams/2014.md
      - 2013年: exams/2013.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.mark
  - toc:
      permalink: true
